### ISSUE TITLE
Re-Computing a Route after a Element was moved?

### ISSUE THREAD

**Issue by rsoika** [eclipse/sprotty#284]
I am using Manhattan Router from sprotty 0.11.0.  in my GLSP project.

There is still a curious behaviour when moving elements and I want to ask if there is an easy way that I force the Manhattan router to re-compute the complete Route after I have moved one of the elements?
 

The problem I observe is the following:

When I place some elements, it is sometimes needed to change the route between two elements form the default route:

![image](https://user-images.githubusercontent.com/1339124/162639052-d874598f-106d-4edb-9a39-fbab68d08b9a.png)

to something like this:

![image](https://user-images.githubusercontent.com/1339124/162638985-c7a4af88-f667-4fb0-b960-9ec86f9cd00f.png)

(This works now great in Sprotty version 0.11 !) 

When now the user decides to move one of the elements to a complete different position, the polyline remembers all its existing routing points:

![image](https://user-images.githubusercontent.com/1339124/162639318-1c7166c1-01f1-4061-99d5-6d2b6827766f.png)

But I would expect to start routing from scratch in such a situation, so that the result is again the default route:

![image](https://user-images.githubusercontent.com/1339124/162639352-be59418e-368c-45dc-aef5-93c89806eaf1.png)

Is this possible? I have seen that there was some discussions with the GLSP team about a new kind of Post-Routing-Action?

**Comment by spoenemann** [comment]
This would require to change the model so all routing points of incident edges are cleared. I would not do that in the base code since it might be unexpected behavior in some cases. Imagine someone has beautifully crafted routes of a dozen incident edges and then moves the node just a little bit... and all those routes are gone. Maybe a more intelligent solution is required, like detecting situations when certain routes should be adapted or cleared.

**Comment by rsoika** [comment]
Thanks, I agree.
