### ISSUE TITLE
Select modifies element order

### ISSUE THREAD

**Issue by tomvdbussche** [eclipse/sprotty#94]
When selecting an element, the `selected` class is added and the element is moved to the last position inside its parent. This can result in elements being hidden which were previously visible.

![select-before-after](https://user-images.githubusercontent.com/5674397/62061515-a13b5680-b227-11e9-82a6-4d85c3305f1a.png)

Left is the initial diagram, right is after clicking the grey node (which is on the same layer as the edges)

**Comment by JanKoehnlein** [comment]
SVG renders children in order, such that the last one appears on top. We change the order to bring the selected element to top. This is something we cannot change.

But it looks like we forget handling attached edges as well. You can work around that by providing your own custom `selectModule` with a custom `SelectCommand` that iterates edges as well and brings them to top as well.

**Comment by spoenemann** [comment]
We could consider introducing some kind of z-index property for model elements, and sort all views by that property during rendering. In that context, we might introduce a default z-index for edges that is higher than the default z-index of other elements.

**Comment by NiklasRentzCAU** [comment]
I vote for this, as that would also solve the issue I created for our project with a very similar scenario as this one. See [here](https://rtsys.informatik.uni-kiel.de/jira/browse/KIPRA-1936).

**Comment by JanKoehnlein** [comment]
The problem is not whether we use a z-index value or the order of children to define z-order, it's rather how we want to modify the z-order of nodes and edges on select. We can consider putting edges always on top, but this yields to strange rendering when the anchor point where an edge connects to a node is covered by another node:

<img width="190" alt="Screen Shot 2019-08-22 at 15 07 08" src="https://user-images.githubusercontent.com/377752/63517068-8b4f4780-c4ee-11e9-83d3-278774535eb9.png">

In the circles example, a selected node is automatically brought to the front, as well as its connecting edges. That feels kind of natural to me. But it doesn't match the use-case of such container nodes as in your example that should always stay in the back. This is why I proposed to have a different SelectCommand instead.

**Comment by spoenemann** [comment]
> Alternatively, we can decouple selection from z-order changes entirely.

That sounds like the cleanest solution to me. The command that handles z-order changes should consider nested graphs properly.
